// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RoboBarCart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1RobaCola', async function() {
    // Test name: 1RobaCola
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1371x900 | 
    await driver.manage().window().setRect({ width: 1371, height: 900 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('2RobaCola', async function() {
    // Test name: 2RobaCola
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1433x900 | 
    await driver.manage().window().setRect({ width: 1433, height: 900 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 5 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 6 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('2Robowine', async function() {
    // Test name: 2Robowine
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1781x838 | 
    await driver.manage().window().setRect({ width: 1781, height: 838 })
    // 3 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 5 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 6 | mouseOver | css=.btn-success | 
    {
      const element = await driver.findElement(By.css(".btn-success"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 7 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 8 | type | id=ageInput | 33
    await driver.findElement(By.id("ageInput")).sendKeys("33")
    // 9 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('2RoboBeer', async function() {
    // Test name: 2RoboBeer
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1781x838 | 
    await driver.manage().window().setRect({ width: 1781, height: 838 })
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 5 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 6 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 7 | type | id=ageInput | 28
    await driver.findElement(By.id("ageInput")).sendKeys("28")
    // 8 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('1Robowine', async function() {
    // Test name: 1Robowine
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1781x838 | 
    await driver.manage().window().setRect({ width: 1781, height: 838 })
    // 3 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | mouseOver | css=.btn-success | 
    {
      const element = await driver.findElement(By.css(".btn-success"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 6 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 7 | type | id=ageInput | 23
    await driver.findElement(By.id("ageInput")).sendKeys("23")
    // 8 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('1RoboCola1Robowine', async function() {
    // Test name: 1RoboCola1Robowine
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1781x838 | 
    await driver.manage().window().setRect({ width: 1781, height: 838 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
    // 5 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 6 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 7 | type | id=ageInput | 22
    await driver.findElement(By.id("ageInput")).sendKeys("22")
    // 8 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('1RoboBeer', async function() {
    // Test name: 1RoboBeer
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1781x838 | 
    await driver.manage().window().setRect({ width: 1781, height: 838 })
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 6 | type | id=ageInput | 34
    await driver.findElement(By.id("ageInput")).sendKeys("34")
    // 7 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
  })
  it('1RoboCola1RoboBeer1Robowine', async function() {
    // Test name: 1RoboCola1RoboBeer1Robowine
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 937x880 | 
    await driver.manage().window().setRect({ width: 937, height: 880 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 5 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
  })
})
